//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomizacaoMoradias.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FileName {
            get {
                return ((string)(this["FileName"]));
            }
            set {
                this["FileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BaseLevelName {
            get {
                return ((string)(this["BaseLevelName"]));
            }
            set {
                this["BaseLevelName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TopLevelName {
            get {
                return ((string)(this["TopLevelName"]));
            }
            set {
                this["TopLevelName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("paredeBranca15cm")]
        public string WallTypeName {
            get {
                return ((string)(this["WallTypeName"]));
            }
            set {
                this["WallTypeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("janelaVeneziana150cm")]
        public string J1 {
            get {
                return ((string)(this["J1"]));
            }
            set {
                this["J1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("janelaCorrerVidro150cm")]
        public string J2 {
            get {
                return ((string)(this["J2"]));
            }
            set {
                this["J2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bandeira60x40")]
        public string J3 {
            get {
                return ((string)(this["J3"]));
            }
            set {
                this["J3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("janelaVeneziana200cm")]
        public string J4 {
            get {
                return ((string)(this["J4"]));
            }
            set {
                this["J4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("janelaCorrerVidro200cm")]
        public string J5 {
            get {
                return ((string)(this["J5"]));
            }
            set {
                this["J5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("portaDeAbrirMadeira80cm")]
        public string P1 {
            get {
                return ((string)(this["P1"]));
            }
            set {
                this["P1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("portaDeAbrirMetalVidro90cm")]
        public string P2 {
            get {
                return ((string)(this["P2"]));
            }
            set {
                this["P2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("portaCorrerMetalVidro160cm")]
        public string P3 {
            get {
                return ((string)(this["P3"]));
            }
            set {
                this["P3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string P4 {
            get {
                return ((string)(this["P4"]));
            }
            set {
                this["P4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("chuveiro")]
        public string H1 {
            get {
                return ((string)(this["H1"]));
            }
            set {
                this["H1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("caixaAcoplada")]
        public string H2 {
            get {
                return ((string)(this["H2"]));
            }
            set {
                this["H2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lavatorioColuna")]
        public string H3 {
            get {
                return ((string)(this["H3"]));
            }
            set {
                this["H3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pia150cm")]
        public string H4 {
            get {
                return ((string)(this["H4"]));
            }
            set {
                this["H4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pia200cm")]
        public string H5 {
            get {
                return ((string)(this["H5"]));
            }
            set {
                this["H5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("maquinaLavar")]
        public string H6 {
            get {
                return ((string)(this["H6"]));
            }
            set {
                this["H6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tanqueLavarRoupa")]
        public string H7 {
            get {
                return ((string)(this["H7"]));
            }
            set {
                this["H7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sofa3Lugares")]
        public string M1 {
            get {
                return ((string)(this["M1"]));
            }
            set {
                this["M1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rackComTV")]
        public string M2 {
            get {
                return ((string)(this["M2"]));
            }
            set {
                this["M2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("poltrona")]
        public string M3 {
            get {
                return ((string)(this["M3"]));
            }
            set {
                this["M3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mesaLateral")]
        public string M4 {
            get {
                return ((string)(this["M4"]));
            }
            set {
                this["M4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mesaJantar")]
        public string M5 {
            get {
                return ((string)(this["M5"]));
            }
            set {
                this["M5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("buffet")]
        public string M6 {
            get {
                return ((string)(this["M6"]));
            }
            set {
                this["M6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pia150cm")]
        public string M7 {
            get {
                return ((string)(this["M7"]));
            }
            set {
                this["M7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("geladeira")]
        public string M8 {
            get {
                return ((string)(this["M8"]));
            }
            set {
                this["M8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fogao4Bocas")]
        public string M9 {
            get {
                return ((string)(this["M9"]));
            }
            set {
                this["M9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("armarioCozinhaBaixo60cm")]
        public string M10 {
            get {
                return ((string)(this["M10"]));
            }
            set {
                this["M10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tanqueLavarRoupa")]
        public string M11 {
            get {
                return ((string)(this["M11"]));
            }
            set {
                this["M11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("maquinaLavar")]
        public string M12 {
            get {
                return ((string)(this["M12"]));
            }
            set {
                this["M12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("camaCasal")]
        public string M13 {
            get {
                return ((string)(this["M13"]));
            }
            set {
                this["M13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("guardaRoupa4Modulos")]
        public string M14 {
            get {
                return ((string)(this["M14"]));
            }
            set {
                this["M14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("camaSolteiro")]
        public string M15 {
            get {
                return ((string)(this["M15"]));
            }
            set {
                this["M15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mesaCabeceira")]
        public string M16 {
            get {
                return ((string)(this["M16"]));
            }
            set {
                this["M16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("guardaRoupa2Modulos")]
        public string M17 {
            get {
                return ((string)(this["M17"]));
            }
            set {
                this["M17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mesaDeEstudo")]
        public string M18 {
            get {
                return ((string)(this["M18"]));
            }
            set {
                this["M18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mesaDeCentro")]
        public string M19 {
            get {
                return ((string)(this["M19"]));
            }
            set {
                this["M19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("armarioCozinhaBaixo120cm")]
        public string M20 {
            get {
                return ((string)(this["M20"]));
            }
            set {
                this["M20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mesaJantar6")]
        public string M21 {
            get {
                return ((string)(this["M21"]));
            }
            set {
                this["M21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("piso10cmCeramico40x40")]
        public string FloorName {
            get {
                return ((string)(this["FloorName"]));
            }
            set {
                this["FloorName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("laje10cmBranca")]
        public string CeilingName {
            get {
                return ((string)(this["CeilingName"]));
            }
            set {
                this["CeilingName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("armarioCozinhaAlto120cm")]
        public string M22 {
            get {
                return ((string)(this["M22"]));
            }
            set {
                this["M22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("armarioCozinhaAlto60cm")]
        public string M23 {
            get {
                return ((string)(this["M23"]));
            }
            set {
                this["M23"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\PropertiesDatabase.mdf;Integrated Security=True")]
        public string PropertiesDatabaseConnectionString {
            get {
                return ((string)(this["PropertiesDatabaseConnectionString"]));
            }
        }
    }
}
